### ISSUE TITLE
Mejora en el código de Backtesting

### ISSUE THREAD

**Issue by echoperenb** [smosqueral/GestionRiesgosFinancieros#12]
Al realizar las pruebas de backtesting del VaR, en ambos casos se corre la función`VaRTest()` repetidas veces para extraer determinados elementos calculados. Esto genera ineficiencias en el código que se pueden corregir fácilmente asignando una variable al resultado general de la función, y luego extrayendo los datos necesarios de la siguiente manera:
**Backtesting normalidad**
`test_norm <- VaRTest(alpha=0.01,actual=RetPS2,VaR=VaRN2*(-1))`
`Backtest[1,1]=test_norm$expected.exceed`
`Backtest[1,2]=test_norm$actual.exceed`
`Backtest[1,3]=test_norm$uc.Decision`
`Backtest[1,4]=test_norm$cc.Decision`

**Backtesting histórico**
`test_hist <- VaRTest(alpha=0.01,actual=RetP3,VaR=VaRH2*(-1))`
`Backtest[2,1]=test_hist$expected.exceed`
`Backtest[2,2]=test_hist$actual.exceed`
`Backtest[2,3]=test_hist$uc.Decision`
`Backtest[2,4]=test_hist$cc.Decision`

Así, se evita correr repetidas veces la misma función, evitando ineficiencias.

**Comment by smosqueral** [comment]
Muchas gracias, ya quedó listo el cambio.
