### ISSUE TITLE
Paquetes en R

### ISSUE THREAD

**Issue by santihegri** [smosqueral/GestionRiesgosFinancieros#3]
En el código de R, hay muchos paquetes que se utilizan pero no se especifica el para qué se llaman. Podría ponerse el paquete justo antes de cuando se necesite o también comentar la función de cada paquete.

**Comment by smosqueral** [comment]
No es óptimo poner los paquetes cada vez que se van a utilizar. En general, es buena práctica poner los paquetes al inicio. 

Queda pendiente la explicación para lo que se utilizada cada paqueta. Por lo tanto, dejo el issue abierto.
