### ISSUE TITLE
Mejora para la extracción de datos en los retornos

### ISSUE THREAD

**Issue by msierrah** [smosqueral/GestionRiesgosFinancieros#4]
En el chunk que va de la fila 343 a 369 se podría mejorar las extracción de los datos de los retornos, ya que lo hacemos por ejemplo con ret[,1] para sacar los retornos de la columna 1 que pertenece al SP500. Pero, si esta columna tiene nombre, para no tener que ir a revisar la tabla y contar en que columna esta para llamarlo de esa forma, podemos poner ret$ y R nos despliega el nombre de todas las columnas y así podemos simplemente seleccionar la que necesitamos.

[![Captura de Pantalla 2022-02-09 a la(s) 10 39 41 a  m](https://user-images.githubusercontent.com/99344106/153237387-29173a43-af94-44a8-9c1e-3393378ad18a.png)
](url)

así quedaría el código en esa parte:

```{r}
X<-as.matrix(ret$GSPC.Adjusted-ret$IRX.Adjusted) 
YY<-ret[,2:11] 
t<-dim(YY)[1] 
n<-dim(YY)[2]
Y<-matrix(0,t,n)

for (i in 1:n){
  Y[,i]<-YY[,i]-ret$IRX.Adjusted}

**Comment by smosqueral** [comment]
Se realizó el cambio en la forma de extraer estos datos.
