### ISSUE TITLE
Alternativa para la agrupación de las estadisticas descriptivas

### ISSUE THREAD

**Issue by jpquiramag** [smosqueral/GestionRiesgosFinancieros#5]
Entre la linea 252 y 273 de **Markdown Blog Clase.Rmd** se realiza el cálculo y agrupación de las estadisticas descriptivas de los precios de manera correcta, sin embargo, se podría realizar una mejora al momento de agrupar los resultados la misma matriz, con el fin de no tener que escribir una linea de código para cada estadistica que se quiera calcular.  A continuación se presenta el código original y luego la altenativa que se propone:

**Código original:**
```{r warning=FALSE}
m <- ncol(sm)
EstDesPrecios <- matrix(,7,m)

for (i in 1:m){
  EstDesPrecios[1,i]=colMins(sm[,i])
  EstDesPrecios[2,i]=colMeans(sm[,i])
  EstDesPrecios[3,i]=colMaxs(sm[,i])
  EstDesPrecios[4,i]=colVars(sm[,i])
  EstDesPrecios[5,i]=colSds(sm[,i])
  EstDesPrecios[6,i]=colSkewness(sm[,i])
  EstDesPrecios[7,i]=colKurtosis(sm[,i])
}

rownames(EstDesPrecios) <- c("Min","Mean","Max","Variance","Sds","Skewness","Kurtosis")
colnames(EstDesPrecios) <- c("SP500","Apple","Microsoft","Amazon","AlphabetA","Tesla","AlphabetC","Meta","NVIDIA","BerkshireHathaway","UnitedHealth","Tbill")

EstDesPrecios %>%
  kable(digits=4) %>%
  kable_styling("striped", full_width = F, position = "center")
```
**Código alternativo:**
```
estadisticas<-c("min","mean","max","var","sd","kurtosis","skewness")
n <- length(estadisticas)
m <- ncol(sm)
EstDesPrecios <- matrix(,nrow=n,ncol=m,dimnames = list(estadisticas,c("SP500","Apple","Microsoft","Amazon","AlphabetA","Tesla","AlphabetC","Meta","NVIDIA","BerkshireHathaway","UnitedHealth","Tbill")))
                                                
for (j in 1:n){
  for(i in 1:m){
      EstDesPrecios[j,i]=colStats(sm[,i], FUN = estadisticas[j])
  }
}

EstDesPrecios %>%
  kable(digits=4) %>%
  kable_styling("striped", full_width = F, position = "center")
```

De esta manera, solo es necesario escribir entre comillas el nombre de las funciones que se desean aplicar a los precios, en el vector **estadisticas**. Luego se calcula la dimensión de dicho vector para que a la hora de crear la matriz **EstDesPrecios**, esta se ajuste automaticamente al número de funciones que vamos a utilizar. Posteriormente, los _ciclos for_ se encargan de rellenar la matriz a partir de una sola instrucción (_colStats_), sin necesidad de escribir una linea para cada función.

Adicionalmente, se puede observar que se propoponen algunos cambios con respecto a la forma en como se asignan los nombres de las filas y columnas de la matriz **EstDesPrecios**, pues en este caso se asignan los nombres en la misma línea en donde se crea la matriz.

**Comment by smosqueral** [comment]
Se realizó el cambio en las estadísticas de los precios y de los retornos.
