### ISSUE TITLE
Problema en la estimación del CAPM

### ISSUE THREAD

**Issue by echoperenb** [smosqueral/GestionRiesgosFinancieros#6]
El problema identificado yace en que, al descargar los datos del Tbill 13 weeks, se está obteniendo una serie que de por sí ya representa los _yields_ del instrumento, por lo que esencialmente estos ya son rendimientos. 

Posteriormente se calculan los rendimientos de todos los instrumentos, lo que para estos bonos no tendría sentido ya que se está estimando la tasa de cambio de un retorno, que en esencia no tiene interpretación. Por este motivo al realizar el gráfico, se puede ver que hay valores que llegan a -400%, o superan el 100%. 

Por este motivo se proponen varios cambios: Inicialmente, el gráfico debería estar de la forma

`plot(sm[,12], main ="Tbill 13 weeks")`

Tanto para los retornos como para el gráfico en niveles, pues son esencialmente lo mismo. 

Ahora, ya que los rendimientos de las demás variables están definidos en porcentaje (o sea, multiplicadas por 100), de forma continua y en términos diarios, es necesario homologar los cálculos como se muestra a continuación: 
**Nota:** Se asumió que la tasa descargada se encuentra en términos NASV por convencionalismo en EEUU
`rf <-(1+ sm[,12]/2)^(1/180)-1
`rf <- log(rf+1)*100`

Adicionalmente, para crear el vector de X que busca encontrar los betas, se debe adaptar de la siguiente manera. 

`X<-as.matrix(ret[,1]-rf)`

Ya que los valores contenidos en la matriz inicial son la tasa libre de riesgo. 

Además, se debe corregir el vector Y de una forma análoga como se muestra a continuación

`for (i in 1:n){
  Y[,i]<-YY[,i]-rf}`

Con esto se efectúa la corrección correspondiente y se mantiene la dinámica del modelo para realizar la estimación del beta.

**Comment by smosqueral** [comment]
Se realizaron las correcciones propuestas.
