### ISSUE TITLE
Parte innecesaria en el cálculo con el método de Montecarlo

### ISSUE THREAD

**Issue by echoperenb** [smosqueral/GestionRiesgosFinancieros#8]
En el cálculo del VaR con el método de Montecarlo, aparece lo siguiente luego de generar los datos aleatorios normales
`L1 <- x1*-1`
Esta línea es innecesaria, dado que la distribución normal usada es simétrica, por lo que multiplicar por -1 los aleatorios generados solo expanden el código y lo hacen ineficiente. 
Es posible hacer lo que sigue solamente cambiando todo lo que dice L1 por x1, ya que así se mantienen los datos originales y no se usa capacidad computacional en exceso.

**Comment by smosqueral** [comment]
De acuerdo. Ya se eliminó esta línea.
