### ISSUE TITLE
Problema con el código de Var Tailfraction

### ISSUE THREAD

**Issue by santihegri** [smosqueral/GestionRiesgosFinancieros#9]
Para hallar el VaR con metodología del valor extremo, la fórmula está mal cuando hay más niveles de significancia. La parte del (1-tailfraction) se reemplazaría con (1-alpha). Se debe comparar con la fórmula de la presentación de Powerpoint para ver cómo coincidirían-

**Comment by smosqueral** [comment]
Se cambió en esta línea tailfraction por alpha. También se cambió la fórmula para que quede igual a la diapositiva.
